# Sample configuration file for Sidekiq.
# Options here can still be overridden by cmd line args.
#   sidekiq -C config.yml
---
:pidfile: tmp/sidekiq.utl.pid
:verbose: false
:logfile: log/sidekiq.log
:queues:
  - [high, 4]
  - [default, 2]
  - [low, 1]
